### ISSUE TITLE
Transfer - Naming and Transfer

### ISSUE THREAD

**Issue by GeoffreyXue** [quarcs-lab/quarcs-bolivia#102]
### Current State
As a result of the transfer, the project site links has broken and some of the links now may not work. Also, the existing deployment process doesn't carry over and must be replicated on this new repository

### TODO
- [ ]  Update the README
- [ ] Update the metadata files (package.json, potentially config files as well)
- [ ] Update Wiki with correct links
- [ ] Update "About Us" page with the correct repository link
- [ ] Update the "How to Contribute?" button on the navbar
